
spring: 
  profiles: 
    active: "@activatedProperties@"
  http: 
    encoding: 
      charset: utf8
    
mybatis: 
  typeAliasesPackage: com.galaxy.transfer.bean
  mapperLocations: classpath:mapper/*.xml
  
web:
  loginFilter:
    excludes: /webjars,/swagger,/api-docs,/login/userLogin,/user/updatePwd,/user/getUserById,/user/getUserResource,/user/getResources,/user/getUserScope,/role/selectRoleIdByUserId,/role/selectRoleCodeByUserId,/depart/getLeafDepartList,/user/getUsersByKey,/user/getUserByIds,/user/findUserByName,/user/getUsersByDepId,/user/getShareUserList,/user/getCreadIdInfo,/depart/getDeptIdByDeptName,/user/resetPasswordForApp,/login/userLoginForApp,/role/getRoleCodeByUserId,/depart/getDeptInfo,/depart/getCareerLineList,/user/getUserList
    
    
    
    
    
    
    